node_js:
- "4"
- "6"
- "8"
- "10"
- "stable"
language: node_js
script:
  - npm run ci
  - 'if [ "$TRAVIS_NODE_VERSION" = "stable" ]; then npm run deps; fi'
after_success: "npm i -g codecov && npm run coverage && codecov"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
