node_js:
- "4"
- "6"
- "8"
- "10"
- "12"
- "stable"
language: node_js
script:
  - xvfb-run --auto-servernum npm run ci
  - 'if [ "$TRAVIS_NODE_VERSION" = "stable" ]; then npm run deps; fi'
after_success: "npm i -g codecov && npm run coverage && codecov"
services:
  - xvfb
